project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "en/*.qmd"
  resources:
    - files/CV-JulioLanda.pdf
    - files/CV-JulioLanda-in.pdf

website:
  title: "Julio Landa" 
  page-footer: 
    center:  "© Julio Landa · 2026 · Código: <a href='https://opensource.org/license/mit/'>MIT</a> · Contenido: <a href='https://creativecommons.org/licenses/by-nc/4.0/'>CC BY‑NC 4.0</a>"
  favicon: images/Perfil.jpg
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: cv.qmd
        text: CV
      - href: publicaciones.qmd
        text: Publicaciones
      - href: proyectos.qmd
        text: Proyectos
      - href: about.qmd
        text: Acerca de mí
    right:
      - text: Idioma
        href: "#"
        aria-label: Language Switch
      - icon: envelope
        aria-label: Email
        href: "mailto:landajulioc@gmail.com"
      - icon: linkedin
        aria-label: LinkedIn
        href: "https://www.linkedin.com/in/JulioLanda4"
      - icon: github
        aria-label: GitHub
        href: "https://github.com/JulioLanda4"
      - icon: link-45deg
        aria-label: ORCID
        href: "https://orcid.org/0009-0006-2067-6624"

format:
  html:
    theme: flatly
    css: styles.css
    include-in-header: lang-pref.html
    include-after-body: project-links.html
    body-attrs:
      data-github-owner: JulioLanda4
    lang: es
    toc: false
